repos:
  - repo: https://github.com/zricethezav/gitleaks
    rev: v8.12.0  # Use the latest stable version
    hooks:
      - id: gitleaks

  - repo: https://github.com/adrienverge/yamllint.git
    rev: v1.29.0  # Use the latest stable version
    hooks:
      - id: yamllint

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0  # Use the latest stable version
    hooks:
      - id: check-merge-conflict
      - id: check-added-large-files
