
name: CI Pipeline

on:
  push:
    branches:
      - 'feature/**'  # Trigger on commits to feature branches
  pull_request:
    branches:
      - main  # Trigger on pull requests to the main branch

jobs:
  linting:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

          #      - name: Check .editorconfig
          #   uses: editorconfig-checker/editorconfig-checker@v2.3.3
      
      - name: Lint Markdown files
        uses: davidanson/markdownlint-cli2-action@v1
        with:
          config_path: .markdownlint.json
          globs: '**/*.{md,markdown}'

  testing:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11.8'
          cache: 'pip'
      - name: Install flask
        run:
          pip install flask
      - name: Run pylint
        run: |
          pip install pylint
          pylint -d C0114,C0115,C0116 $(git ls-files '*.py')
      - name: Run black for code formatting
        run: |
          pip install black
          black --check app
      - name: Run unit tests
        run: |
          cd app/
          python -m unittest app_test.py
  security:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Run gitleaks for secrets scanning
        uses: zricethezav/gitleaks-action@v1
      
      - name: Check if SONAR_TOKEN is set
        run: |
          if [ -z "${{ secrets.SONAR_TOKEN }}" ]; then
            echo "Error: SONAR_TOKEN is not set!"
            exit 1
          fi
        
      - name: Run SonarCloud SAST
        uses: SonarSource/sonarcloud-github-action@v3.1.0
        
        env:
         SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
         SONAR_HOST_URL: https://sonarcloud.io  
        with:
          args: >
            -Dsonar.projectKey=zigzig234_devops-programme
            -Dsonar.organization=zigzig234
            -Dsonar.pullrequest.key=${{ github.event.pull_request.number }}
            -Dsonar.pullrequest.branch=${{ github.head_ref }}
            -Dsonar.pullrequest.base=${{ github.base_ref }} 
      
      - name: Run Snyk for dependency security scan
        uses: snyk/actions/python@master
        with:
          args: --severity-threshold=high
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
     
      - name: Snyk Fix Vulnerabilities
        run: snyk fix --all-projects
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}


  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        run: |
          IMAGE_TAG=${{ github.sha }}
          docker build -t ${{ secrets.DOCKER_USERNAME }}/flask-app:$IMAGE_TAG .
      - name: Scan Docker image with Trivy
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: ${{ secrets.DOCKER_USERNAME }}/flask-app:${{ github.sha }}
        id: trivy

      - name: Push Docker image to Docker Hub
        if: steps.trivy.outputs.vulnerabilities != 'CRITICAL'  # Only push if no critical vulnerabilities
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/flask-app:${{ github.sha }}
